<?php

/**
 * BillingAddress
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * BillingAddress
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class BillingAddress implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "addressLine1" : {
      "type" : "string"
    },
    "addressLine2" : {
      "type" : "string"
    },
    "addressLine3" : {
      "type" : "string"
    },
    "city" : {
      "type" : "string"
    },
    "county" : {
      "type" : "string"
    },
    "district" : {
      "type" : "string"
    },
    "stateOrRegion" : {
      "type" : "string"
    },
    "postalCode" : {
      "type" : "string"
    },
    "countryCode" : {
      "type" : "string"
    },
    "phoneNumber" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var string $name */
    private $name;

    /** @var string $addressLine1 */
    private $addressLine1;

    /** @var string $addressLine2 */
    private $addressLine2;

    /** @var string $addressLine3 */
    private $addressLine3;

    /** @var string $city */
    private $city;

    /** @var string $county */
    private $county;

    /** @var string $district */
    private $district;

    /** @var string $stateOrRegion */
    private $stateOrRegion;

    /** @var string $postalCode */
    private $postalCode;

    /** @var string $countryCode */
    private $countryCode;

    /** @var string $phoneNumber */
    private $phoneNumber;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
