<?php

/**
 * CaptureResponse
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * CaptureResponse
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CaptureResponse implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "chargeId" : {
      "type" : "string"
    },
    "chargeAmount" : {
      "$ref" : "#/components/schemas/ChargeAmount"
    },
    "chargePermissionId" : {
      "type" : "string"
    },
    "captureAmount" : {
      "$ref" : "#/components/schemas/CaptureAmount"
    },
    "refundedAmount" : {
      "$ref" : "#/components/schemas/RefundedAmount"
    },
    "softDescriptor" : {
      "type" : "string"
    },
    "statusDetail" : {
      "$ref" : "#/components/schemas/StatusDetail"
    },
    "convertedAmount" : {
      "type" : "string"
    },
    "conversionRate" : {
      "type" : "string"
    },
    "creationTimestamp" : {
      "type" : "string"
    },
    "expirationTimestamp" : {
      "type" : "string"
    },
    "releaseEnvironment" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var string $chargeId */
    private $chargeId;

    /** @var \OpenAPIServer\Model\ChargeAmount $chargeAmount */
    private $chargeAmount;

    /** @var string $chargePermissionId */
    private $chargePermissionId;

    /** @var \OpenAPIServer\Model\CaptureAmount $captureAmount */
    private $captureAmount;

    /** @var \OpenAPIServer\Model\RefundedAmount $refundedAmount */
    private $refundedAmount;

    /** @var string $softDescriptor */
    private $softDescriptor;

    /** @var \OpenAPIServer\Model\StatusDetail $statusDetail */
    private $statusDetail;

    /** @var string $convertedAmount */
    private $convertedAmount;

    /** @var string $conversionRate */
    private $conversionRate;

    /** @var string $creationTimestamp */
    private $creationTimestamp;

    /** @var string $expirationTimestamp */
    private $expirationTimestamp;

    /** @var string $releaseEnvironment */
    private $releaseEnvironment;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
