<?php

/**
 * CustomerData
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * CustomerData
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CustomerData implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "checkoutSessionId" : {
      "type" : "string"
    },
    "webCheckoutDetail" : {
      "$ref" : "#/components/schemas/webCheckoutDetail"
    },
    "productType" : {
      "type" : "string"
    },
    "paymentDetail" : {
      "$ref" : "#/components/schemas/PaymentDetails"
    },
    "merchantMetadata" : {
      "$ref" : "#/components/schemas/MerchantMetadata"
    },
    "buyer" : {
      "$ref" : "#/components/schemas/Buyer"
    },
    "supplementaryData" : {
      "type" : "string"
    },
    "paymentPreferences" : {
      "$ref" : "#/components/schemas/PaymentPreferences"
    },
    "statusDetail" : {
      "$ref" : "#/components/schemas/StatusDetail"
    },
    "shippingAddress" : {
      "$ref" : "#/components/schemas/ShippingAddress"
    },
    "platformId" : {
      "type" : "string"
    },
    "chargePermissionId" : {
      "type" : "string"
    },
    "chargeId" : {
      "type" : "string"
    },
    "creationTimestamp" : {
      "type" : "string"
    },
    "expirationTimestamp" : {
      "type" : "string"
    },
    "storeId" : {
      "type" : "string"
    },
    "releaseEnvironment" : {
      "type" : "string"
    },
    "deliverySpecifications" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var string $checkoutSessionId */
    private $checkoutSessionId;

    /** @var \OpenAPIServer\Model\WebCheckoutDetail $webCheckoutDetail */
    private $webCheckoutDetail;

    /** @var string $productType */
    private $productType;

    /** @var \OpenAPIServer\Model\PaymentDetails $paymentDetail */
    private $paymentDetail;

    /** @var \OpenAPIServer\Model\MerchantMetadata $merchantMetadata */
    private $merchantMetadata;

    /** @var \OpenAPIServer\Model\Buyer $buyer */
    private $buyer;

    /** @var string $supplementaryData */
    private $supplementaryData;

    /** @var object[] $paymentPreferences */
    private $paymentPreferences;

    /** @var \OpenAPIServer\Model\StatusDetail $statusDetail */
    private $statusDetail;

    /** @var \OpenAPIServer\Model\ShippingAddress $shippingAddress */
    private $shippingAddress;

    /** @var string $platformId */
    private $platformId;

    /** @var string $chargePermissionId */
    private $chargePermissionId;

    /** @var string $chargeId */
    private $chargeId;

    /** @var string $creationTimestamp */
    private $creationTimestamp;

    /** @var string $expirationTimestamp */
    private $expirationTimestamp;

    /** @var string $storeId */
    private $storeId;

    /** @var string $releaseEnvironment */
    private $releaseEnvironment;

    /** @var string $deliverySpecifications */
    private $deliverySpecifications;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
