<?php

/**
 * MerchantMetadata
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * MerchantMetadata
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class MerchantMetadata implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "merchantReferenceId" : {
      "type" : "string",
      "description" : "Demandware generated order ID"
    },
    "merchantStoreName" : {
      "type" : "string"
    },
    "noteToBuyer" : {
      "type" : "string"
    },
    "customInformation" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var string $merchantReferenceId Demandware generated order ID*/
    private $merchantReferenceId;

    /** @var string $merchantStoreName */
    private $merchantStoreName;

    /** @var string $noteToBuyer */
    private $noteToBuyer;

    /** @var string $customInformation */
    private $customInformation;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
