<?php

/**
 * PaymentDetails
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * PaymentDetails
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class PaymentDetails implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "paymentIntent" : {
      "type" : "string"
    },
    "canHandlePendingAuthorization" : {
      "type" : "boolean"
    },
    "chargeAmount" : {
      "$ref" : "#/components/schemas/ChargeAmount"
    },
    "softDescriptor" : {
      "type" : "string"
    },
    "presentmentCurrency" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var string $paymentIntent */
    private $paymentIntent;

    /** @var bool $canHandlePendingAuthorization */
    private $canHandlePendingAuthorization;

    /** @var \OpenAPIServer\Model\ChargeAmount $chargeAmount */
    private $chargeAmount;

    /** @var string $softDescriptor */
    private $softDescriptor;

    /** @var string $presentmentCurrency */
    private $presentmentCurrency;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
