<?php

/**
 * SessionPayload
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * SessionPayload
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SessionPayload implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "storeId", "webCheckoutDetail" ],
  "type" : "object",
  "properties" : {
    "webCheckoutDetail" : {
      "$ref" : "#/components/schemas/webCheckoutDetail"
    },
    "storeId" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var \OpenAPIServer\Model\WebCheckoutDetail $webCheckoutDetail */
    private $webCheckoutDetail;

    /** @var string $storeId */
    private $storeId;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
