<?php

/**
 * WebCheckoutDetail
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * WebCheckoutDetail
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class WebCheckoutDetail implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "checkoutResultReturnUrl", "checkoutReviewReturnUrl" ],
  "type" : "object",
  "properties" : {
    "checkoutReviewReturnUrl" : {
      "type" : "string"
    },
    "checkoutResultReturnUrl" : {
      "type" : "string"
    },
    "amazonPayRedirectUrl" : {
      "type" : "string",
      "description" : "The URL generated by Amazon where we need to redirect the customer after the authorize method has been called (The url is returned in the response of the order/authorize method)"
    }
  }
}
SCHEMA;

    /** @var string $checkoutReviewReturnUrl */
    private $checkoutReviewReturnUrl;

    /** @var string $checkoutResultReturnUrl */
    private $checkoutResultReturnUrl;

    /** @var string $amazonPayRedirectUrl The URL generated by Amazon where we need to redirect the customer after the authorize method has been called (The url is returned in the response of the order/authorize method)*/
    private $amazonPayRedirectUrl;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
