<?php

/**
 * CaptureResponseTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Horze Amazon Pay REST API
 *
 * A Restful API that works as a gateaway for Amazon PAY
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\CaptureResponse;

/**
 * CaptureResponseTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\CaptureResponse
 */
class CaptureResponseTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CaptureResponse"
     */
    public function testCaptureResponse()
    {
        $testCaptureResponse = new CaptureResponse();
    }

    /**
     * Test attribute "chargeId"
     */
    public function testPropertyChargeId()
    {
    }

    /**
     * Test attribute "chargeAmount"
     */
    public function testPropertyChargeAmount()
    {
    }

    /**
     * Test attribute "chargePermissionId"
     */
    public function testPropertyChargePermissionId()
    {
    }

    /**
     * Test attribute "captureAmount"
     */
    public function testPropertyCaptureAmount()
    {
    }

    /**
     * Test attribute "refundedAmount"
     */
    public function testPropertyRefundedAmount()
    {
    }

    /**
     * Test attribute "softDescriptor"
     */
    public function testPropertySoftDescriptor()
    {
    }

    /**
     * Test attribute "statusDetail"
     */
    public function testPropertyStatusDetail()
    {
    }

    /**
     * Test attribute "convertedAmount"
     */
    public function testPropertyConvertedAmount()
    {
    }

    /**
     * Test attribute "conversionRate"
     */
    public function testPropertyConversionRate()
    {
    }

    /**
     * Test attribute "creationTimestamp"
     */
    public function testPropertyCreationTimestamp()
    {
    }

    /**
     * Test attribute "expirationTimestamp"
     */
    public function testPropertyExpirationTimestamp()
    {
    }

    /**
     * Test attribute "releaseEnvironment"
     */
    public function testPropertyReleaseEnvironment()
    {
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaObject = CaptureResponse::getOpenApiSchema();
        $schemaArr = CaptureResponse::getOpenApiSchema(true);
        $this->assertIsObject($schemaObject);
        $this->assertIsArray($schemaArr);
    }
}
