<?php

/**
 * CustomerDataTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Horze Amazon Pay REST API
 *
 * A Restful API that works as a gateaway for Amazon PAY
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\CustomerData;

/**
 * CustomerDataTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\CustomerData
 */
class CustomerDataTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerData"
     */
    public function testCustomerData()
    {
        $testCustomerData = new CustomerData();
    }

    /**
     * Test attribute "checkoutSessionId"
     */
    public function testPropertyCheckoutSessionId()
    {
    }

    /**
     * Test attribute "webCheckoutDetail"
     */
    public function testPropertyWebCheckoutDetail()
    {
    }

    /**
     * Test attribute "productType"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "paymentDetail"
     */
    public function testPropertyPaymentDetail()
    {
    }

    /**
     * Test attribute "merchantMetadata"
     */
    public function testPropertyMerchantMetadata()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "supplementaryData"
     */
    public function testPropertySupplementaryData()
    {
    }

    /**
     * Test attribute "paymentPreferences"
     */
    public function testPropertyPaymentPreferences()
    {
    }

    /**
     * Test attribute "statusDetail"
     */
    public function testPropertyStatusDetail()
    {
    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "platformId"
     */
    public function testPropertyPlatformId()
    {
    }

    /**
     * Test attribute "chargePermissionId"
     */
    public function testPropertyChargePermissionId()
    {
    }

    /**
     * Test attribute "chargeId"
     */
    public function testPropertyChargeId()
    {
    }

    /**
     * Test attribute "creationTimestamp"
     */
    public function testPropertyCreationTimestamp()
    {
    }

    /**
     * Test attribute "expirationTimestamp"
     */
    public function testPropertyExpirationTimestamp()
    {
    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "releaseEnvironment"
     */
    public function testPropertyReleaseEnvironment()
    {
    }

    /**
     * Test attribute "deliverySpecifications"
     */
    public function testPropertyDeliverySpecifications()
    {
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaObject = CustomerData::getOpenApiSchema();
        $schemaArr = CustomerData::getOpenApiSchema(true);
        $this->assertIsObject($schemaObject);
        $this->assertIsArray($schemaArr);
    }
}
