<?php

/**
 * MerchantMetadataTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Horze Amazon Pay REST API
 *
 * A Restful API that works as a gateaway for Amazon PAY
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\MerchantMetadata;

/**
 * MerchantMetadataTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\MerchantMetadata
 */
class MerchantMetadataTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MerchantMetadata"
     */
    public function testMerchantMetadata()
    {
        $testMerchantMetadata = new MerchantMetadata();
    }

    /**
     * Test attribute "merchantReferenceId"
     */
    public function testPropertyMerchantReferenceId()
    {
    }

    /**
     * Test attribute "merchantStoreName"
     */
    public function testPropertyMerchantStoreName()
    {
    }

    /**
     * Test attribute "noteToBuyer"
     */
    public function testPropertyNoteToBuyer()
    {
    }

    /**
     * Test attribute "customInformation"
     */
    public function testPropertyCustomInformation()
    {
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaObject = MerchantMetadata::getOpenApiSchema();
        $schemaArr = MerchantMetadata::getOpenApiSchema(true);
        $this->assertIsObject($schemaObject);
        $this->assertIsArray($schemaArr);
    }
}
