<?php

/**
 * ShippingAddressTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Horze Amazon Pay REST API
 *
 * A Restful API that works as a gateaway for Amazon PAY
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\ShippingAddress;

/**
 * ShippingAddressTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\ShippingAddress
 */
class ShippingAddressTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingAddress"
     */
    public function testShippingAddress()
    {
        $testShippingAddress = new ShippingAddress();
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "addressLine1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "addressLine2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "addressLine3"
     */
    public function testPropertyAddressLine3()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
    }

    /**
     * Test attribute "stateOrRegion"
     */
    public function testPropertyStateOrRegion()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "countryCode"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaObject = ShippingAddress::getOpenApiSchema();
        $schemaArr = ShippingAddress::getOpenApiSchema(true);
        $this->assertIsObject($schemaObject);
        $this->assertIsArray($schemaArr);
    }
}
