<?php

/**
 * DefaultApiTest
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Horze Amazon Pay REST API
 *
 * A Restful API that works as a gateaway for Amazon PAY
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customerGet
     *
     * .
     *
     * @covers ::customerGet
     */
    public function testCustomerGet()
    {
    }

    /**
     * Test case for orderAuthorizePost
     *
     * .
     *
     * @covers ::orderAuthorizePost
     */
    public function testOrderAuthorizePost()
    {
    }

    /**
     * Test case for orderCaptureGet
     *
     * .
     *
     * @covers ::orderCaptureGet
     */
    public function testOrderCaptureGet()
    {
    }

    /**
     * Test case for orderCapturePost
     *
     * .
     *
     * @covers ::orderCapturePost
     */
    public function testOrderCapturePost()
    {
    }

    /**
     * Test case for orderRefundGet
     *
     * .
     *
     * @covers ::orderRefundGet
     */
    public function testOrderRefundGet()
    {
    }

    /**
     * Test case for orderRefundPost
     *
     * .
     *
     * @covers ::orderRefundPost
     */
    public function testOrderRefundPost()
    {
    }

    /**
     * Test case for sessionNewPost
     *
     * .
     *
     * @covers ::sessionNewPost
     */
    public function testSessionNewPost()
    {
    }
}
